version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 699475927716.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=699475927716.dkr.ecr.ap-south-1.amazonaws.com/pawan-carvilla
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t pawan-carvilla .
      - docker tag pawan-carvilla:latest 699475927716.dkr.ecr.ap-south-1.amazonaws.com/pawan-carvilla:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 699475927716.dkr.ecr.ap-south-1.amazonaws.com/pawan-carvilla:latest
